/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Row } from "./interfaces/components/table";
export { Row } from "./interfaces/components/table";
export namespace Components {
    interface DplButton {
        "disabled": boolean;
        "name"?: string;
    }
    interface DplTable {
        /**
          * @default []
         */
        "columns": string[];
        /**
          * @default []
         */
        "rows": Row[];
    }
}
export interface DplButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDplButtonElement;
}
declare global {
    interface HTMLDplButtonElementEventMap {
        "dplClick": void;
    }
    interface HTMLDplButtonElement extends Components.DplButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDplButtonElementEventMap>(type: K, listener: (this: HTMLDplButtonElement, ev: DplButtonCustomEvent<HTMLDplButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDplButtonElementEventMap>(type: K, listener: (this: HTMLDplButtonElement, ev: DplButtonCustomEvent<HTMLDplButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDplButtonElement: {
        prototype: HTMLDplButtonElement;
        new (): HTMLDplButtonElement;
    };
    interface HTMLDplTableElement extends Components.DplTable, HTMLStencilElement {
    }
    var HTMLDplTableElement: {
        prototype: HTMLDplTableElement;
        new (): HTMLDplTableElement;
    };
    interface HTMLElementTagNameMap {
        "dpl-button": HTMLDplButtonElement;
        "dpl-table": HTMLDplTableElement;
    }
}
declare namespace LocalJSX {
    interface DplButton {
        "disabled": boolean;
        "name"?: string;
        "onDplClick"?: (event: DplButtonCustomEvent<void>) => void;
    }
    interface DplTable {
        /**
          * @default []
         */
        "columns"?: string[];
        /**
          * @default []
         */
        "rows"?: Row[];
    }
    interface IntrinsicElements {
        "dpl-button": DplButton;
        "dpl-table": DplTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dpl-button": LocalJSX.DplButton & JSXBase.HTMLAttributes<HTMLDplButtonElement>;
            "dpl-table": LocalJSX.DplTable & JSXBase.HTMLAttributes<HTMLDplTableElement>;
        }
    }
}
