/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DplButton {
    }
}
declare global {
    interface HTMLDplButtonElement extends Components.DplButton, HTMLStencilElement {
    }
    var HTMLDplButtonElement: {
        prototype: HTMLDplButtonElement;
        new (): HTMLDplButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dpl-button": HTMLDplButtonElement;
    }
}
declare namespace LocalJSX {
    interface DplButton {
    }
    interface IntrinsicElements {
        "dpl-button": DplButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dpl-button": LocalJSX.DplButton & JSXBase.HTMLAttributes<HTMLDplButtonElement>;
        }
    }
}
